In [1]:
# necessary imports
import pandas as pd

In [2]:
# Define paths to raw CSV files
raw_data_path = '../data/raw/'


def load_dataset(path):
    df = pd.read_csv(f'{raw_data_path}{path}')
    return df

# Load all raw CSV files
account_profiles_df = load_dataset("account_profiles.csv")
fraud_patterns_df = load_dataset("fraud_patterns.csv")
network_edges_df = load_dataset("network_edges.csv")
time_series_stats_df = load_dataset("time_series_stats.csv")
transactions_df = load_dataset("transactions.csv")

print("All raw CSV files loaded.")

All raw CSV files loaded.

In [3]:
print('--- account_profiles_df ---\nShape:', account_profiles_df.shape)
print('Columns:', account_profiles_df.columns.tolist())
display(account_profiles_df.head())
print('Info:')
account_profiles_df.info()
print('\nMissing Values:')
display(account_profiles_df.isnull().sum().to_frame(name='missing_count'))

--- account_profiles_df ---
Shape: (50000, 23)
Columns: ['account_id', 'account_age_days', 'credit_limit', 'home_country', 'risk_score', 'is_high_risk', 'avg_txn_amount', 'avg_monthly_txns', 'has_2fa', 'account_type', 'total_transactions', 'total_amount', 'avg_amount', 'max_amount', 'fraud_count', 'fraud_amount', 'pct_foreign', 'avg_velocity', 'unique_countries', 'unique_categories', 'avg_ip_risk', 'fraud_rate', 'is_fraudster']

,account_id,account_age_days,credit_limit,home_country,risk_score,is_high_risk,avg_txn_amount,avg_monthly_txns,has_2fa,account_type,...,max_amount,fraud_count,fraud_amount,pct_foreign,avg_velocity,unique_countries,unique_categories,avg_ip_risk,fraud_rate,is_fraudster
0,ACC0000001,353,2171.42,US,16.5,0,90.82,71.1,1,personal,...,740.46,0.0,0.00,0.35,1.27,9.0,11.0,22.98,0.0,0.0
1,ACC0000002,2831,3031.38,US,25.4,0,63.78,7.4,1,business,...,186.13,1.0,186.13,0.50,4.00,2.0,2.0,52.45,0.5,1.0
2,ACC0000003,2399,7533.75,US,10.6,0,72.18,31.9,0,personal,...,1175.86,0.0,0.00,0.17,1.44,3.0,8.0,15.50,0.0,0.0
3,ACC0000004,1618,4821.94,US,20.7,0,53.64,16.6,1,personal,...,2753.31,0.0,0.00,0.33,1.11,4.0,10.0,19.01,0.0,0.0
4,ACC0000005,1597,3355.10,US,30.6,0,168.44,32.0,1,personal,...,718.61,0.0,0.00,0.42,0.95,7.0,12.0,26.71,0.0,0.0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   account_id          50000 non-null  str
 1   account_age_days    50000 non-null  int64
 2   credit_limit        50000 non-null  float64
 3   home_country        50000 non-null  str
 4   risk_score          50000 non-null  float64
 5   is_high_risk        50000 non-null  int64
 6   avg_txn_amount      50000 non-null  float64
 7   avg_monthly_txns    50000 non-null  float64
 8   has_2fa             50000 non-null  int64
 9   account_type        50000 non-null  str
 10  total_transactions  50000 non-null  float64
 11  total_amount        50000 non-null  float64
 12  avg_amount          50000 non-null  float64
 13  max_amount          50000 non-null  float64
 14  fraud_count         50000 non-null  float64
 15  fraud_amount        50000 non-null  float64
 16  pct_foreign         50000 non-null  float64
 17  avg_velocity        50000 non-null  float64
 18  unique_countries    50000 non-null  float64
 19  unique_categories   50000 non-null  float64
 20  avg_ip_risk         50000 non-null  float64
 21  fraud_rate          50000 non-null  float64
 22  is_fraudster        50000 non-null  float64
dtypes: float64(17), int64(3), str(3)
memory usage: 8.8 MB

Missing Values:

                    missing_count
account_id                      0
account_age_days                0
credit_limit                    0
home_country                    0
risk_score                      0
is_high_risk                    0
avg_txn_amount                  0
avg_monthly_txns                0
has_2fa                         0
account_type                    0
total_transactions              0
total_amount                    0
avg_amount                      0
max_amount                      0
fraud_count                     0
fraud_amount                    0
pct_foreign                     0
avg_velocity                    0
unique_countries                0
unique_categories               0
avg_ip_risk                     0
fraud_rate                      0
is_fraudster                    0

In [4]:
print('\n--- fraud_patterns_df ---\nShape:', fraud_patterns_df.shape)
print('Columns:', fraud_patterns_df.columns.tolist())
display(fraud_patterns_df)
print('Info:')
fraud_patterns_df.info()
print('\nMissing Values:')
display(fraud_patterns_df.isnull().sum().to_frame(name='missing_count'))

--- fraud_patterns_df ---
Shape: (7, 12)
Columns: ['fraud_pattern', 'description', 'transaction_count', 'fraud_share_pct', 'avg_amount', 'median_amount', 'pct_night_0_5', 'pct_foreign', 'pct_card_not_present', 'avg_velocity_1h', 'avg_ip_risk', 'pct_no_2fa']

,fraud_pattern,description,transaction_count,fraud_share_pct,avg_amount,median_amount,pct_night_0_5,pct_foreign,pct_card_not_present,avg_velocity_1h,avg_ip_risk,pct_no_2fa
0,card_not_present,Online/CNP fraud — stolen card details used wi...,5982,34.89,771.78,268.63,41.32,58.06,73.12,3.98,55.26,42.24
1,account_takeover,Fraudster gains access to legitimate account v...,3432,20.02,1203.13,436.78,40.88,59.64,74.24,3.96,55.89,41.72
2,card_present_stolen,Physical card stolen and used at POS terminals,3120,18.20,556.84,200.27,40.83,57.24,73.17,3.95,54.99,40.61
3,friendly_fraud,Legitimate cardholder disputes valid transacti...,1726,10.07,352.61,120.80,38.99,55.97,74.68,3.93,54.91,42.47
4,atm_fraud,ATM skimming or card trapping to clone card,1216,7.09,466.26,164.53,40.87,60.44,76.23,4.04,55.60,39.39
5,money_laundering,Series of transactions to disguise illicit fun...,1011,5.90,93.59,35.42,40.36,60.63,72.21,3.97,55.79,44.02
6,identity_theft,New account opened using stolen personal infor...,656,3.83,1163.50,387.26,38.72,57.62,75.30,3.93,55.14,42.23

Info:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fraud_pattern         7 non-null      str
 1   description           7 non-null      str
 2   transaction_count     7 non-null      int64
 3   fraud_share_pct       7 non-null      float64
 4   avg_amount            7 non-null      float64
 5   median_amount         7 non-null      float64
 6   pct_night_0_5         7 non-null      float64
 7   pct_foreign           7 non-null      float64
 8   pct_card_not_present  7 non-null      float64
 9   avg_velocity_1h       7 non-null      float64
 10  avg_ip_risk           7 non-null      float64
 11  pct_no_2fa            7 non-null      float64
dtypes: float64(9), int64(1), str(2)
memory usage: 804.0 bytes

Missing Values:

                      missing_count
fraud_pattern                     0
description                       0
transaction_count                 0
fraud_share_pct                   0
avg_amount                        0
median_amount                     0
pct_night_0_5                     0
pct_foreign                       0
pct_card_not_present              0
avg_velocity_1h                   0
avg_ip_risk                       0
pct_no_2fa                        0

In [5]:
print('\n--- network_edges_df ---\nShape:', network_edges_df.shape)
print('Columns:', network_edges_df.columns.tolist())
display(network_edges_df.head())
print('Info:')
network_edges_df.info()
print('\nMissing Values:')
display(network_edges_df.isnull().sum().to_frame(name='missing_count'))

--- network_edges_df ---
Shape: (7411, 6)
Columns: ['account_a', 'account_b', 'shared_type', 'connection_count', 'ring_id', 'both_fraud']

,account_a,account_b,shared_type,connection_count,ring_id,both_fraud
0,ACC0017803,ACC0040032,phone,7,RING0001,1
1,ACC0017803,ACC0042246,email_domain,12,RING0001,1
2,ACC0017803,ACC0029491,phone,13,RING0001,1
3,ACC0017803,ACC0022213,phone,12,RING0001,1
4,ACC0017803,ACC0007601,ip_address,14,RING0001,1

Info:
<class 'pandas.DataFrame'>
RangeIndex: 7411 entries, 0 to 7410
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account_a         7411 non-null   str
 1   account_b         7411 non-null   str
 2   shared_type       7411 non-null   str
 3   connection_count  7411 non-null   int64
 4   ring_id           4411 non-null   str
 5   both_fraud        7411 non-null   int64
dtypes: int64(2), str(4)
memory usage: 347.5 KB

Missing Values:

                  missing_count
account_a                     0
account_b                     0
shared_type                   0
connection_count              0
ring_id                    3000
both_fraud                    0

In [6]:

print('\n--- time_series_stats_df ---\nShape:', time_series_stats_df.shape)
print('Columns:', time_series_stats_df.columns.tolist())
display(time_series_stats_df.head())
print('Info:')
time_series_stats_df.info()
print('\nMissing Values:')
display(time_series_stats_df.isnull().sum().to_frame(name='missing_count'))

--- time_series_stats_df ---
Shape: (26280, 10)
Columns: ['hour', 'transaction_count', 'fraud_count', 'total_amount', 'avg_amount', 'avg_ip_risk', 'fraud_rate', 'hour_of_day', 'day_of_week', 'is_weekend']

,hour,transaction_count,fraud_count,total_amount,avg_amount,avg_ip_risk,fraud_rate,hour_of_day,day_of_week,is_weekend
0,2022-01-01 00:00:00,40,1,9341.66,233.54,19.92,0.025000,0,5,1
1,2022-01-01 01:00:00,43,0,6295.77,146.41,20.32,0.000000,1,5,1
2,2022-01-01 02:00:00,41,1,10763.95,262.54,22.13,0.024390,2,5,1
3,2022-01-01 03:00:00,34,0,9354.50,275.13,22.00,0.000000,3,5,1
4,2022-01-01 04:00:00,39,2,5897.09,151.21,25.87,0.051282,4,5,1

Info:
<class 'pandas.DataFrame'>
RangeIndex: 26280 entries, 0 to 26279
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hour               26280 non-null  str
 1   transaction_count  26280 non-null  int64
 2   fraud_count        26280 non-null  int64
 3   total_amount       26280 non-null  float64
 4   avg_amount         26280 non-null  float64
 5   avg_ip_risk        26280 non-null  float64
 6   fraud_rate         26280 non-null  float64
 7   hour_of_day        26280 non-null  int64
 8   day_of_week        26280 non-null  int64
 9   is_weekend         26280 non-null  int64
dtypes: float64(4), int64(5), str(1)
memory usage: 2.0 MB

Missing Values:

                   missing_count
hour                           0
transaction_count              0
fraud_count                    0
total_amount                   0
avg_amount                     0
avg_ip_risk                    0
fraud_rate                     0
hour_of_day                    0
day_of_week                    0
is_weekend                     0

In [7]:
print('\n--- transactions_df ---\nShape:', transactions_df.shape)
print('Columns:', transactions_df.columns.tolist())
display(transactions_df.head())
print('Info:')
transactions_df.info()
print('\nMissing Values:')
display(transactions_df.isnull().sum().to_frame(name='missing_count'))

--- transactions_df ---
Shape: (1000000, 23)
Columns: ['transaction_id', 'account_id', 'timestamp', 'hour_of_day', 'day_of_week', 'is_weekend', 'amount', 'merchant_category', 'mcc_code', 'merchant_country', 'card_present', 'device_type', 'device_known', 'ip_risk_score', 'is_foreign_txn', 'time_since_last_s', 'velocity_1h', 'amount_vs_avg_ratio', 'account_age_days', 'has_2fa', 'credit_limit', 'is_fraud', 'fraud_pattern']

,transaction_id,account_id,timestamp,hour_of_day,day_of_week,is_weekend,amount,merchant_category,mcc_code,merchant_country,...,ip_risk_score,is_foreign_txn,time_since_last_s,velocity_1h,amount_vs_avg_ratio,account_age_days,has_2fa,credit_limit,is_fraud,fraud_pattern
0,TXN000000001,ACC0016173,2023-02-21 08:02:38,8,1,0,168.42,travel,4511,CA,...,53.2,1,21,3,2.6423,3256,1,3958.46,0,NaN
1,TXN000000002,ACC0011196,2024-05-12 23:13:34,23,6,1,85.78,online_retail,5999,AU,...,25.3,1,234,1,0.7279,1527,1,3553.35,0,NaN
2,TXN000000003,ACC0001181,2023-09-22 23:28:21,23,4,0,20.15,pharmacy,5912,CA,...,21.3,1,85,1,0.1851,2230,1,4362.57,0,NaN
3,TXN000000004,ACC0037105,2022-09-28 23:26:38,23,2,0,62.49,grocery,5411,US,...,13.7,0,98,0,1.5223,1863,1,3194.84,0,NaN
4,TXN000000005,ACC0028471,2023-02-23 17:54:13,17,3,0,71.68,online_retail,5999,US,...,9.7,0,721,2,0.7724,1728,0,11850.06,0,NaN

Info:
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 23 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   transaction_id       1000000 non-null  str
 1   account_id           1000000 non-null  str
 2   timestamp            1000000 non-null  str
 3   hour_of_day          1000000 non-null  int64
 4   day_of_week          1000000 non-null  int64
 5   is_weekend           1000000 non-null  int64
 6   amount               1000000 non-null  float64
 7   merchant_category    1000000 non-null  str
 8   mcc_code             1000000 non-null  int64
 9   merchant_country     1000000 non-null  str
 10  card_present         1000000 non-null  int64
 11  device_type          1000000 non-null  str
 12  device_known         1000000 non-null  int64
 13  ip_risk_score        1000000 non-null  float64
 14  is_foreign_txn       1000000 non-null  int64
 15  time_since_last_s    1000000 non-null  int64
 16  velocity_1h          1000000 non-null  int64
 17  amount_vs_avg_ratio  1000000 non-null  float64
 18  account_age_days     1000000 non-null  int64
 19  has_2fa              1000000 non-null  int64
 20  credit_limit         1000000 non-null  float64
 21  is_fraud             1000000 non-null  int64
 22  fraud_pattern        17143 non-null    str
dtypes: float64(4), int64(12), str(7)
memory usage: 175.5 MB

Missing Values:

                     missing_count
transaction_id                   0
account_id                       0
timestamp                        0
hour_of_day                      0
day_of_week                      0
is_weekend                       0
amount                           0
merchant_category                0
mcc_code                         0
merchant_country                 0
card_present                     0
device_type                      0
device_known                     0
ip_risk_score                    0
is_foreign_txn                   0
time_since_last_s                0
velocity_1h                      0
amount_vs_avg_ratio              0
account_age_days                 0
has_2fa                          0
credit_limit                     0
is_fraud                         0
fraud_pattern               982857